# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/dma_wrapper.xdc

# Block Designs: bd/dma/dma.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma || ORIG_REF_NAME==dma}]

# IP: bd/dma/ip/dma_processing_system7_0_0/dma_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_processing_system7_0_0 || ORIG_REF_NAME==dma_processing_system7_0_0}]

# IP: bd/dma/ip/dma_axi_cdma_0_0/dma_axi_cdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_axi_cdma_0_0 || ORIG_REF_NAME==dma_axi_cdma_0_0}]

# IP: bd/dma/ip/dma_axi_mem_intercon_0/dma_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_axi_mem_intercon_0 || ORIG_REF_NAME==dma_axi_mem_intercon_0}]

# IP: bd/dma/ip/dma_proc_sys_reset_0/dma_proc_sys_reset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_proc_sys_reset_0 || ORIG_REF_NAME==dma_proc_sys_reset_0}]

# IP: bd/dma/ip/dma_init_cdma_0_0/dma_init_cdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_init_cdma_0_0 || ORIG_REF_NAME==dma_init_cdma_0_0}]

# IP: bd/dma/ip/dma_axi_bram_ctrl_0_0/dma_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_axi_bram_ctrl_0_0 || ORIG_REF_NAME==dma_axi_bram_ctrl_0_0}]

# IP: bd/dma/ip/dma_processing_system7_0_axi_periph_1/dma_processing_system7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_processing_system7_0_axi_periph_1 || ORIG_REF_NAME==dma_processing_system7_0_axi_periph_1}]

# IP: bd/dma/ip/dma_xbar_2/dma_xbar_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_xbar_2 || ORIG_REF_NAME==dma_xbar_2}]

# IP: bd/dma/ip/dma_xbar_3/dma_xbar_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_xbar_3 || ORIG_REF_NAME==dma_xbar_3}]

# IP: bd/dma/ip/dma_axi_crossbar_0_4/dma_axi_crossbar_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_axi_crossbar_0_4 || ORIG_REF_NAME==dma_axi_crossbar_0_4}]

# IP: bd/dma/ip/dma_axi_bram_ctrl_0_bram_0/dma_axi_bram_ctrl_0_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==dma_axi_bram_ctrl_0_bram_0}]

# IP: bd/dma/ip/dma_acp_0_0/dma_acp_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_acp_0_0 || ORIG_REF_NAME==dma_acp_0_0}]

# IP: bd/dma/ip/dma_reg_status_0_0/dma_reg_status_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_reg_status_0_0 || ORIG_REF_NAME==dma_reg_status_0_0}]

# IP: bd/dma/ip/dma_reg_init_0_1/dma_reg_init_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_reg_init_0_1 || ORIG_REF_NAME==dma_reg_init_0_1}]

# IP: bd/dma/ip/dma_ADC_emul_0_1/dma_ADC_emul_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_ADC_emul_0_1 || ORIG_REF_NAME==dma_ADC_emul_0_1}]

# IP: bd/dma/ip/dma_auto_pc_1181/dma_auto_pc_1181.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_auto_pc_1181 || ORIG_REF_NAME==dma_auto_pc_1181}]

# IP: bd/dma/ip/dma_auto_ds_876/dma_auto_ds_876.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_auto_ds_876 || ORIG_REF_NAME==dma_auto_ds_876}]

# IP: bd/dma/ip/dma_auto_pc_1182/dma_auto_pc_1182.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_auto_pc_1182 || ORIG_REF_NAME==dma_auto_pc_1182}]

# IP: bd/dma/ip/dma_auto_us_877/dma_auto_us_877.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_auto_us_877 || ORIG_REF_NAME==dma_auto_us_877}]

# IP: bd/dma/ip/dma_auto_pc_1183/dma_auto_pc_1183.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_auto_pc_1183 || ORIG_REF_NAME==dma_auto_pc_1183}]

# IP: bd/dma/ip/dma_auto_us_878/dma_auto_us_878.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_auto_us_878 || ORIG_REF_NAME==dma_auto_us_878}]

# IP: bd/dma/ip/dma_auto_pc_1184/dma_auto_pc_1184.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_auto_pc_1184 || ORIG_REF_NAME==dma_auto_pc_1184}]

# XDC: bd/dma/ip/dma_processing_system7_0_0/dma_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dma_processing_system7_0_0 || ORIG_REF_NAME==dma_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/dma/ip/dma_axi_cdma_0_0/dma_axi_cdma_0_0_ooc.xdc

# XDC: bd/dma/ip/dma_axi_cdma_0_0/dma_axi_cdma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dma_axi_cdma_0_0 || ORIG_REF_NAME==dma_axi_cdma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/dma/ip/dma_proc_sys_reset_0/dma_proc_sys_reset_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dma_proc_sys_reset_0 || ORIG_REF_NAME==dma_proc_sys_reset_0}] {/U0 }]/U0 ]]

# XDC: bd/dma/ip/dma_proc_sys_reset_0/dma_proc_sys_reset_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dma_proc_sys_reset_0 || ORIG_REF_NAME==dma_proc_sys_reset_0}] {/U0 }]/U0 ]]

# XDC: bd/dma/ip/dma_proc_sys_reset_0/dma_proc_sys_reset_0_ooc.xdc

# XDC: bd/dma/ip/dma_axi_bram_ctrl_0_0/dma_axi_bram_ctrl_0_0_ooc.xdc

# XDC: bd/dma/ip/dma_xbar_2/dma_xbar_2_ooc.xdc

# XDC: bd/dma/ip/dma_xbar_3/dma_xbar_3_ooc.xdc

# XDC: bd/dma/ip/dma_axi_crossbar_0_4/dma_axi_crossbar_0_4_ooc.xdc

# XDC: bd/dma/ip/dma_axi_bram_ctrl_0_bram_0/dma_axi_bram_ctrl_0_bram_0_ooc.xdc

# XDC: bd/dma/ip/dma_auto_pc_1181/dma_auto_pc_1181_ooc.xdc

# XDC: bd/dma/ip/dma_auto_ds_876/dma_auto_ds_876_ooc.xdc

# XDC: bd/dma/ip/dma_auto_ds_876/dma_auto_ds_876_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dma_auto_ds_876 || ORIG_REF_NAME==dma_auto_ds_876}] {/inst }]/inst ]]

# XDC: bd/dma/ip/dma_auto_pc_1182/dma_auto_pc_1182_ooc.xdc

# XDC: bd/dma/ip/dma_auto_us_877/dma_auto_us_877_ooc.xdc

# XDC: bd/dma/ip/dma_auto_us_877/dma_auto_us_877_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dma_auto_us_877 || ORIG_REF_NAME==dma_auto_us_877}] {/inst }]/inst ]]

# XDC: bd/dma/ip/dma_auto_pc_1183/dma_auto_pc_1183_ooc.xdc

# XDC: bd/dma/ip/dma_auto_us_878/dma_auto_us_878_ooc.xdc

# XDC: bd/dma/ip/dma_auto_us_878/dma_auto_us_878_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dma_auto_us_878 || ORIG_REF_NAME==dma_auto_us_878}] {/inst }]/inst ]]

# XDC: bd/dma/ip/dma_auto_pc_1184/dma_auto_pc_1184_ooc.xdc

# XDC: bd/dma/dma_ooc.xdc
