# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/dma_wrapper.xdc

# Block Designs: bd/dma/dma.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma || ORIG_REF_NAME==dma}]

# IP: bd/dma/ip/dma_processing_system7_0_0/dma_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_processing_system7_0_0 || ORIG_REF_NAME==dma_processing_system7_0_0}]

# IP: bd/dma/ip/dma_axi_cdma_0_0/dma_axi_cdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_axi_cdma_0_0 || ORIG_REF_NAME==dma_axi_cdma_0_0}]

# IP: bd/dma/ip/dma_axi_mem_intercon_0/dma_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_axi_mem_intercon_0 || ORIG_REF_NAME==dma_axi_mem_intercon_0}]

# IP: bd/dma/ip/dma_proc_sys_reset_0/dma_proc_sys_reset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_proc_sys_reset_0 || ORIG_REF_NAME==dma_proc_sys_reset_0}]

# IP: bd/dma/ip/dma_init_cdma_0_0/dma_init_cdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_init_cdma_0_0 || ORIG_REF_NAME==dma_init_cdma_0_0}]

# IP: bd/dma/ip/dma_axi_bram_ctrl_0_0/dma_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_axi_bram_ctrl_0_0 || ORIG_REF_NAME==dma_axi_bram_ctrl_0_0}]

# IP: bd/dma/ip/dma_processing_system7_0_axi_periph_1/dma_processing_system7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_processing_system7_0_axi_periph_1 || ORIG_REF_NAME==dma_processing_system7_0_axi_periph_1}]

# IP: bd/dma/ip/dma_xbar_2/dma_xbar_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_xbar_2 || ORIG_REF_NAME==dma_xbar_2}]

# IP: bd/dma/ip/dma_xbar_3/dma_xbar_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_xbar_3 || ORIG_REF_NAME==dma_xbar_3}]

# IP: bd/dma/ip/dma_axi_bram_ctrl_0_bram_0/dma_axi_bram_ctrl_0_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==dma_axi_bram_ctrl_0_bram_0}]

# IP: bd/dma/ip/dma_acp_0_0/dma_acp_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_acp_0_0 || ORIG_REF_NAME==dma_acp_0_0}]

# IP: bd/dma/ip/dma_reg_status_0_0/dma_reg_status_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_reg_status_0_0 || ORIG_REF_NAME==dma_reg_status_0_0}]

# IP: bd/dma/ip/dma_reg_init_0_1/dma_reg_init_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_reg_init_0_1 || ORIG_REF_NAME==dma_reg_init_0_1}]

# IP: bd/dma/ip/dma_ADC_emul_0_1/dma_ADC_emul_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_ADC_emul_0_1 || ORIG_REF_NAME==dma_ADC_emul_0_1}]

# IP: bd/dma/ip/dma_m01_data_fifo_16/dma_m01_data_fifo_16.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_m01_data_fifo_16 || ORIG_REF_NAME==dma_m01_data_fifo_16}]

# IP: bd/dma/ip/dma_auto_pc_1529/dma_auto_pc_1529.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_auto_pc_1529 || ORIG_REF_NAME==dma_auto_pc_1529}]

# IP: bd/dma/ip/dma_auto_ds_1137/dma_auto_ds_1137.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_auto_ds_1137 || ORIG_REF_NAME==dma_auto_ds_1137}]

# IP: bd/dma/ip/dma_auto_pc_1530/dma_auto_pc_1530.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_auto_pc_1530 || ORIG_REF_NAME==dma_auto_pc_1530}]

# IP: bd/dma/ip/dma_auto_rs_6/dma_auto_rs_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_auto_rs_6 || ORIG_REF_NAME==dma_auto_rs_6}]

# IP: bd/dma/ip/dma_auto_us_1138/dma_auto_us_1138.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_auto_us_1138 || ORIG_REF_NAME==dma_auto_us_1138}]

# IP: bd/dma/ip/dma_auto_pc_1531/dma_auto_pc_1531.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_auto_pc_1531 || ORIG_REF_NAME==dma_auto_pc_1531}]

# IP: bd/dma/ip/dma_auto_us_df_1139/dma_auto_us_df_1139.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_auto_us_df_1139 || ORIG_REF_NAME==dma_auto_us_df_1139}]

# IP: bd/dma/ip/dma_auto_pc_1532/dma_auto_pc_1532.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_auto_pc_1532 || ORIG_REF_NAME==dma_auto_pc_1532}]

# XDC: bd/dma/ip/dma_processing_system7_0_0/dma_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dma_processing_system7_0_0 || ORIG_REF_NAME==dma_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/dma/ip/dma_axi_cdma_0_0/dma_axi_cdma_0_0_ooc.xdc

# XDC: bd/dma/ip/dma_axi_cdma_0_0/dma_axi_cdma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dma_axi_cdma_0_0 || ORIG_REF_NAME==dma_axi_cdma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/dma/ip/dma_proc_sys_reset_0/dma_proc_sys_reset_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dma_proc_sys_reset_0 || ORIG_REF_NAME==dma_proc_sys_reset_0}] {/U0 }]/U0 ]]

# XDC: bd/dma/ip/dma_proc_sys_reset_0/dma_proc_sys_reset_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dma_proc_sys_reset_0 || ORIG_REF_NAME==dma_proc_sys_reset_0}] {/U0 }]/U0 ]]

# XDC: bd/dma/ip/dma_proc_sys_reset_0/dma_proc_sys_reset_0_ooc.xdc

# XDC: bd/dma/ip/dma_axi_bram_ctrl_0_0/dma_axi_bram_ctrl_0_0_ooc.xdc

# XDC: bd/dma/ip/dma_xbar_2/dma_xbar_2_ooc.xdc

# XDC: bd/dma/ip/dma_xbar_3/dma_xbar_3_ooc.xdc

# XDC: bd/dma/ip/dma_axi_bram_ctrl_0_bram_0/dma_axi_bram_ctrl_0_bram_0_ooc.xdc

# XDC: bd/dma/ip/dma_m01_data_fifo_16/dma_m01_data_fifo_16_ooc.xdc

# XDC: bd/dma/ip/dma_auto_pc_1529/dma_auto_pc_1529_ooc.xdc

# XDC: bd/dma/ip/dma_auto_ds_1137/dma_auto_ds_1137_ooc.xdc

# XDC: bd/dma/ip/dma_auto_ds_1137/dma_auto_ds_1137_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dma_auto_ds_1137 || ORIG_REF_NAME==dma_auto_ds_1137}] {/inst }]/inst ]]

# XDC: bd/dma/ip/dma_auto_pc_1530/dma_auto_pc_1530_ooc.xdc

# XDC: bd/dma/ip/dma_auto_rs_6/dma_auto_rs_6_ooc.xdc

# XDC: bd/dma/ip/dma_auto_us_1138/dma_auto_us_1138_ooc.xdc

# XDC: bd/dma/ip/dma_auto_us_1138/dma_auto_us_1138_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dma_auto_us_1138 || ORIG_REF_NAME==dma_auto_us_1138}] {/inst }]/inst ]]

# XDC: bd/dma/ip/dma_auto_pc_1531/dma_auto_pc_1531_ooc.xdc

# XDC: bd/dma/ip/dma_auto_us_df_1139/dma_auto_us_df_1139_ooc.xdc

# XDC: bd/dma/ip/dma_auto_us_df_1139/dma_auto_us_df_1139_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dma_auto_us_df_1139 || ORIG_REF_NAME==dma_auto_us_df_1139}] {/inst }]/inst ]]

# XDC: bd/dma/ip/dma_auto_pc_1532/dma_auto_pc_1532_ooc.xdc

# XDC: bd/dma/dma_ooc.xdc
