# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/dma_wrapper.xdc

# Block Designs: bd/dma/dma.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma || ORIG_REF_NAME==dma}]

# IP: bd/dma/ip/dma_processing_system7_0_0/dma_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_processing_system7_0_0 || ORIG_REF_NAME==dma_processing_system7_0_0}]

# IP: bd/dma/ip/dma_axi_cdma_0_0/dma_axi_cdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_axi_cdma_0_0 || ORIG_REF_NAME==dma_axi_cdma_0_0}]

# IP: bd/dma/ip/dma_axi_mem_intercon_0/dma_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_axi_mem_intercon_0 || ORIG_REF_NAME==dma_axi_mem_intercon_0}]

# IP: bd/dma/ip/dma_proc_sys_reset_0/dma_proc_sys_reset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_proc_sys_reset_0 || ORIG_REF_NAME==dma_proc_sys_reset_0}]

# IP: bd/dma/ip/dma_init_cdma_0_0/dma_init_cdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_init_cdma_0_0 || ORIG_REF_NAME==dma_init_cdma_0_0}]

# IP: bd/dma/ip/dma_axi_bram_ctrl_0_0/dma_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_axi_bram_ctrl_0_0 || ORIG_REF_NAME==dma_axi_bram_ctrl_0_0}]

# IP: bd/dma/ip/dma_processing_system7_0_axi_periph_1/dma_processing_system7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_processing_system7_0_axi_periph_1 || ORIG_REF_NAME==dma_processing_system7_0_axi_periph_1}]

# IP: bd/dma/ip/dma_xbar_2/dma_xbar_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_xbar_2 || ORIG_REF_NAME==dma_xbar_2}]

# IP: bd/dma/ip/dma_xbar_3/dma_xbar_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_xbar_3 || ORIG_REF_NAME==dma_xbar_3}]

# IP: bd/dma/ip/dma_axi_crossbar_0_4/dma_axi_crossbar_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_axi_crossbar_0_4 || ORIG_REF_NAME==dma_axi_crossbar_0_4}]

# IP: bd/dma/ip/dma_axi_bram_ctrl_0_bram_0/dma_axi_bram_ctrl_0_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==dma_axi_bram_ctrl_0_bram_0}]

# IP: bd/dma/ip/dma_acp_0_0/dma_acp_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_acp_0_0 || ORIG_REF_NAME==dma_acp_0_0}]

# IP: bd/dma/ip/dma_reg_status_0_0/dma_reg_status_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_reg_status_0_0 || ORIG_REF_NAME==dma_reg_status_0_0}]

# IP: bd/dma/ip/dma_auto_pc_634/dma_auto_pc_634.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_auto_pc_634 || ORIG_REF_NAME==dma_auto_pc_634}]

# IP: bd/dma/ip/dma_auto_ds_465/dma_auto_ds_465.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_auto_ds_465 || ORIG_REF_NAME==dma_auto_ds_465}]

# IP: bd/dma/ip/dma_auto_pc_635/dma_auto_pc_635.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_auto_pc_635 || ORIG_REF_NAME==dma_auto_pc_635}]

# IP: bd/dma/ip/dma_auto_us_466/dma_auto_us_466.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_auto_us_466 || ORIG_REF_NAME==dma_auto_us_466}]

# IP: bd/dma/ip/dma_auto_pc_636/dma_auto_pc_636.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_auto_pc_636 || ORIG_REF_NAME==dma_auto_pc_636}]

# IP: bd/dma/ip/dma_auto_us_467/dma_auto_us_467.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_auto_us_467 || ORIG_REF_NAME==dma_auto_us_467}]

# IP: bd/dma/ip/dma_auto_pc_637/dma_auto_pc_637.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_auto_pc_637 || ORIG_REF_NAME==dma_auto_pc_637}]

# XDC: bd/dma/ip/dma_processing_system7_0_0/dma_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dma_processing_system7_0_0 || ORIG_REF_NAME==dma_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/dma/ip/dma_axi_cdma_0_0/dma_axi_cdma_0_0_ooc.xdc

# XDC: bd/dma/ip/dma_axi_cdma_0_0/dma_axi_cdma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dma_axi_cdma_0_0 || ORIG_REF_NAME==dma_axi_cdma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/dma/ip/dma_proc_sys_reset_0/dma_proc_sys_reset_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dma_proc_sys_reset_0 || ORIG_REF_NAME==dma_proc_sys_reset_0}] {/U0 }]/U0 ]]

# XDC: bd/dma/ip/dma_proc_sys_reset_0/dma_proc_sys_reset_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dma_proc_sys_reset_0 || ORIG_REF_NAME==dma_proc_sys_reset_0}] {/U0 }]/U0 ]]

# XDC: bd/dma/ip/dma_proc_sys_reset_0/dma_proc_sys_reset_0_ooc.xdc

# XDC: bd/dma/ip/dma_axi_bram_ctrl_0_0/dma_axi_bram_ctrl_0_0_ooc.xdc

# XDC: bd/dma/ip/dma_xbar_2/dma_xbar_2_ooc.xdc

# XDC: bd/dma/ip/dma_xbar_3/dma_xbar_3_ooc.xdc

# XDC: bd/dma/ip/dma_axi_crossbar_0_4/dma_axi_crossbar_0_4_ooc.xdc

# XDC: bd/dma/ip/dma_axi_bram_ctrl_0_bram_0/dma_axi_bram_ctrl_0_bram_0_ooc.xdc

# XDC: bd/dma/ip/dma_auto_pc_634/dma_auto_pc_634_ooc.xdc

# XDC: bd/dma/ip/dma_auto_ds_465/dma_auto_ds_465_ooc.xdc

# XDC: bd/dma/ip/dma_auto_ds_465/dma_auto_ds_465_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dma_auto_ds_465 || ORIG_REF_NAME==dma_auto_ds_465}] {/inst }]/inst ]]

# XDC: bd/dma/ip/dma_auto_pc_635/dma_auto_pc_635_ooc.xdc

# XDC: bd/dma/ip/dma_auto_us_466/dma_auto_us_466_ooc.xdc

# XDC: bd/dma/ip/dma_auto_us_466/dma_auto_us_466_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dma_auto_us_466 || ORIG_REF_NAME==dma_auto_us_466}] {/inst }]/inst ]]

# XDC: bd/dma/ip/dma_auto_pc_636/dma_auto_pc_636_ooc.xdc

# XDC: bd/dma/ip/dma_auto_us_467/dma_auto_us_467_ooc.xdc

# XDC: bd/dma/ip/dma_auto_us_467/dma_auto_us_467_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dma_auto_us_467 || ORIG_REF_NAME==dma_auto_us_467}] {/inst }]/inst ]]

# XDC: bd/dma/ip/dma_auto_pc_637/dma_auto_pc_637_ooc.xdc

# XDC: bd/dma/dma_ooc.xdc
