# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/dmas_wrapper.xdc

# Block Designs: bd/dmas/dmas.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dmas || ORIG_REF_NAME==dmas}]

# IP: bd/dmas/ip/dmas_processing_system7_0_0/dmas_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dmas_processing_system7_0_0 || ORIG_REF_NAME==dmas_processing_system7_0_0}]

# IP: bd/dmas/ip/dmas_axi_dma_0_0/dmas_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dmas_axi_dma_0_0 || ORIG_REF_NAME==dmas_axi_dma_0_0}]

# IP: bd/dmas/ip/dmas_stream_acp_0_3/dmas_stream_acp_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dmas_stream_acp_0_3 || ORIG_REF_NAME==dmas_stream_acp_0_3}]

# IP: bd/dmas/ip/dmas_ADC_emul_0_1/dmas_ADC_emul_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dmas_ADC_emul_0_1 || ORIG_REF_NAME==dmas_ADC_emul_0_1}]

# IP: bd/dmas/ip/dmas_axi_mem_intercon_4/dmas_axi_mem_intercon_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dmas_axi_mem_intercon_4 || ORIG_REF_NAME==dmas_axi_mem_intercon_4}]

# IP: bd/dmas/ip/dmas_proc_sys_reset_2/dmas_proc_sys_reset_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dmas_proc_sys_reset_2 || ORIG_REF_NAME==dmas_proc_sys_reset_2}]

# IP: bd/dmas/ip/dmas_init_axi_dma_0_0/dmas_init_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dmas_init_axi_dma_0_0 || ORIG_REF_NAME==dmas_init_axi_dma_0_0}]

# IP: bd/dmas/ip/dmas_processing_system7_0_axi_periph_5/dmas_processing_system7_0_axi_periph_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dmas_processing_system7_0_axi_periph_5 || ORIG_REF_NAME==dmas_processing_system7_0_axi_periph_5}]

# IP: bd/dmas/ip/dmas_init_axi_dma_0_axi_periph_6/dmas_init_axi_dma_0_axi_periph_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dmas_init_axi_dma_0_axi_periph_6 || ORIG_REF_NAME==dmas_init_axi_dma_0_axi_periph_6}]

# IP: bd/dmas/ip/dmas_xbar_9/dmas_xbar_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dmas_xbar_9 || ORIG_REF_NAME==dmas_xbar_9}]

# IP: bd/dmas/ip/dmas_axi_crossbar_0_10/dmas_axi_crossbar_0_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dmas_axi_crossbar_0_10 || ORIG_REF_NAME==dmas_axi_crossbar_0_10}]

# IP: bd/dmas/ip/dmas_reg_status_0_0/dmas_reg_status_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dmas_reg_status_0_0 || ORIG_REF_NAME==dmas_reg_status_0_0}]

# IP: bd/dmas/ip/dmas_auto_pc_146/dmas_auto_pc_146.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dmas_auto_pc_146 || ORIG_REF_NAME==dmas_auto_pc_146}]

# IP: bd/dmas/ip/dmas_auto_us_73/dmas_auto_us_73.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dmas_auto_us_73 || ORIG_REF_NAME==dmas_auto_us_73}]

# IP: bd/dmas/ip/dmas_auto_pc_147/dmas_auto_pc_147.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dmas_auto_pc_147 || ORIG_REF_NAME==dmas_auto_pc_147}]

# XDC: bd/dmas/ip/dmas_processing_system7_0_0/dmas_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dmas_processing_system7_0_0 || ORIG_REF_NAME==dmas_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/dmas/ip/dmas_axi_dma_0_0/dmas_axi_dma_0_0_ooc.xdc

# XDC: bd/dmas/ip/dmas_axi_dma_0_0/dmas_axi_dma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dmas_axi_dma_0_0 || ORIG_REF_NAME==dmas_axi_dma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/dmas/ip/dmas_axi_dma_0_0/dmas_axi_dma_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dmas_axi_dma_0_0 || ORIG_REF_NAME==dmas_axi_dma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/dmas/ip/dmas_proc_sys_reset_2/dmas_proc_sys_reset_2_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dmas_proc_sys_reset_2 || ORIG_REF_NAME==dmas_proc_sys_reset_2}] {/U0 }]/U0 ]]

# XDC: bd/dmas/ip/dmas_proc_sys_reset_2/dmas_proc_sys_reset_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dmas_proc_sys_reset_2 || ORIG_REF_NAME==dmas_proc_sys_reset_2}] {/U0 }]/U0 ]]

# XDC: bd/dmas/ip/dmas_proc_sys_reset_2/dmas_proc_sys_reset_2_ooc.xdc

# XDC: bd/dmas/ip/dmas_xbar_9/dmas_xbar_9_ooc.xdc

# XDC: bd/dmas/ip/dmas_axi_crossbar_0_10/dmas_axi_crossbar_0_10_ooc.xdc

# XDC: bd/dmas/ip/dmas_auto_pc_146/dmas_auto_pc_146_ooc.xdc

# XDC: bd/dmas/ip/dmas_auto_us_73/dmas_auto_us_73_ooc.xdc

# XDC: bd/dmas/ip/dmas_auto_us_73/dmas_auto_us_73_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dmas_auto_us_73 || ORIG_REF_NAME==dmas_auto_us_73}] {/inst }]/inst ]]

# XDC: bd/dmas/ip/dmas_auto_pc_147/dmas_auto_pc_147_ooc.xdc

# XDC: bd/dmas/dmas_ooc.xdc
